loader:
    verbose: true
logging:
    level:
        org:
            springframework:
spring:
    aop:
        proxy-target-class: true
    data:
        mongodb:
#            authentication-database: reflex
            database: shop
            host: ds255787.mlab.com
            username: shopadmin
            password: testing123
            port: 55787
            repositories:
                enabled: true
    jpa:
        properties:
            hibernate:
                show_sql: true
